### ISSUE TITLE
case sensitivity

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#1]
can we make it case insensitive? that way, we can support /functions/get-dbalowercase redirect in addition to dbatools.io/Get-ProperCase

**Comment by niphlod** [comment]
yup, lemme check it quick

**Comment by niphlod** [comment]
done

**Comment by potatoqualitee** [comment]
awesome! fixed on my side too. with mobile fixed, it looks like you can do your announcements tomorrow, @ClaudioESSilva !
