### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#11]
I love the sidebar for https://dbachecks.readthedocs.io/en/latest/

where we can add other relevant shortcuts like the various related posts (Cms, Xevents, DA, etc) 

can we have something similar? merci

**Comment by niphlod** [comment]
we can but should we ? 
It'd be quite hard to inject usefully yet another piece of content in a quite crowded sidebar, dbachecks has not 400ish functions. 
Maybe it'd be best to either forge an index of sorts (but IMHO for the moment it's better covered by https://dbatools.io/commands/ , till we 'll have proper tagging ) or linking to such posts via each function's help (so it'll be available also for users not jumping on docs.dbatools.io straight away)  ?

**Comment by potatoqualitee** [comment]
What if it were like max 5 URLs? or 3? It is a long sidebar,b ut you take care of it well with tha search filter

**Comment by niphlod** [comment]
Not an "adding problem", it's just "design wise" how to "highlight" links
to external resources(if I got that right they'll be blogposts), and how to
"relate" them to one or more doc functions.

Il gio 4 ott 2018, 10:41 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by potatoqualitee** [comment]
Global links will be good - so the same 3-5 will show up every time

**Comment by niphlod** [comment]
then we can make them fixed in the index.html .... what 3-5 links are, specifically ?

**Comment by niphlod** [comment]
heads up @potatoqualitee

**Comment by potatoqualitee** [comment]
oh sorry mmmmmm lets see 

dbatools.io/offline
dbatools.io/start
dbatools.io/secure

and maybe
dbatools.io/clone
dbatools.io/cms
dbatools.io/snapshots
