### ISSUE TITLE
Can we get pretty metadata?

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#13]
Helps with twitter cards:

![image](https://user-images.githubusercontent.com/8278033/46580720-8d213100-ca2a-11e8-8507-312956291e23.png)

**Comment by niphlod** [comment]
not sure what metadata we want !?

**Comment by niphlod** [comment]
okay, I think I got it. we can but it'll be just one, as twitter bot doesn't execute javascript

**Comment by niphlod** [comment]
okay, so we have "photo", "title", "description" and link. Do we have an idea of what the twitter card for docs.dbatools.io should "say" ?

**Comment by wsmelton** [comment]
I'd keep it simple "dbatools doc's site" but that is just me :)

**Comment by niphlod** [comment]
can you test ? I just pushed the page with the - hopefully correct - metadata

**Comment by niphlod** [comment]
@potatoqualitee : this is in (albeit with basic metadata). Feel free to reopen if we need to change something
