### ISSUE TITLE
Syntax at the bottom?

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/docs#15]
Just verifying why syntax is at the bottom of the page? Can it be at the top, after the description at least so we don't have to scroll to the bottom of the page.

**Comment by niphlod** [comment]
@potatoqualitee made a few arrangements on "sections" a while ago. Didn't bother to touch from that moment on.

Frankly, I don't have any personal preference, but IMHO it should either go just before or just after examples, irregardless of "other sections"

**Comment by wsmelton** [comment]
Doesn't Get-Help put it after the description? The pattern used on PS Docs site it is near the top. It would also be nice if there could be a line break for those that have parameter sets... Think it will make it easier to read.
