### ISSUE TITLE
Exclude Invoke-SqlCmd2

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/docs#16]
https://docs.dbatools.io/#Invoke-Sqlcmd2

Being that we can't modify the documentation on this command to our standard can it just be removed from our documentation? I mean it is an external command we simply include in the module for convenience.

**Comment by niphlod** [comment]
I'm still unsure why the command is still in....... it's not required anymore and won't ever be 1.0 ready. Also, we have invoke-dbaquery for some time now, and that one should be used instead.

@potatoqualitee : this (the removal) has been asked a few times already... why are we still keeping it in ?

**Comment by wsmelton** [comment]
I don't is either one but believe most thought/think the dbaquery is just a wrapper. If it is not then I'm all for dropping the other one. (The repo for sqlcmd2 is not getting attention from the PRs and such anyway.)

**Comment by niphlod** [comment]
invoke-dbaquery was born that way but now glues our connect-magic with what invoke-sqlcmd2 has for query building and resultset packaging. as such, it's a better replacement and "follows our standards"/"adheres to our tooling" better. 
Whenever a new feature is requested on each one, both will benefit (either we backport there or we import from)
