### ISSUE TITLE
Report if a command is not supported on Mac / Linux

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#17]
I'll be adding this to the commands that cant support linux like the Performance Monitoring commands. The code is `if (Test-NotWindows) { return }`

Can that be added to json and thus docs somehow?

**Comment by wsmelton** [comment]
Would it not be better to just not have the command load as a function on non windows?

Seem to recall that is how some other modules did.

**Comment by wsmelton** [comment]
I think it is easier to control the list in the psm1 or say create a json file of the command for Windows. Then on import just have those excluded as exported function.

**Comment by potatoqualitee** [comment]
that wouldn't address our docs issue, and as an end-user, i would like to know that it is not supported, instead of it not existing. i wish there was a `BeforeAll` equivalent of a Module, it'd be nice not to have to add this to every command, but to a list.

**Comment by wsmelton** [comment]
For docs we just have to maintain a list. Having to add code just to validate if a command should be used does not seem proper to me.

SqlServer module I recall has setup where they won't load all commands on non-windows.

Other option just off the top is folder structure. If windows based commands are in one folder?

**Comment by potatoqualitee** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmm maybe a list can do mmmm

**Comment by niphlod** [comment]
note to self

>> so `Platform: Windows, Linux, macOS` for 250ish and `Platform: Windows only` for the remainder

`$script:noncoresmo` is `Windows only`

**Comment by niphlod** [comment]
once https://github.com/sqlcollaborative/dbatools/pull/4807 is in, this can be closed.
