### ISSUE TITLE
multiline weirdness

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#18]
I thought the docs would be wrong for this command since the last example is broken i the webpage

https://docs.dbatools.io/#New-DbaAvailabilityGroup

but it is good in the docs. Something inserted a line in the json or the website and it's no longer copyable.

**Comment by wsmelton** [comment]
Fixed with sqlcollaborative/dbatools#4746

When you have multi-line it cannot be tabbed out, has to be just like you see it in the console window for the copy function to work in docs page. It ignores the `>>` we add when the text has a tab before it.

**Comment by wsmelton** [comment]
An example of this properly is on Restore command for example 10.

**Comment by potatoqualitee** [comment]
ty 💯
