### ISSUE TITLE
CmdLets not exported

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#19]
we have two real C# cmdlets, Select-DbaObject and Set-DbatoolsConfig, which export in cmdletstoexport in the psd1 instead of functionstoexport. Anyway, they aren't being added to the json.

**Comment by niphlod** [comment]
ouch. we "select" `$dbamodule.ExportedCommands.Values | Where-Object CommandType -EQ 'Function'` .
Select-DbaObject is a Cmdlet, and it pops up if we do `-in @(function, cmdlet)`.
However, no synopsys nor description....
 
Set-DbatoolsConfig ..... where it can be found ?

**Comment by potatoqualitee** [comment]
interresting, its in dbatools.dll oh wow, it doesnt have help. i'd need to figure out how to do it. probably an xml

**Comment by niphlod** [comment]
should have been fixed by wsmelton

**Comment by potatoqualitee** [comment]
Thank you @wsmelton 🙇 !
