### ISSUE TITLE
google alert - Mobile Usability issues detected

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#25]
Search Console has identified that your site is affected by 3 new Mobile Usability related issues. This means that Mobile Usability may be negatively affected in Google Search results. We encourage you to fix these issues.

Top new issues found, ordered by number of affected pages:

* Viewport not set
* Clickable elements too close together
* Text too small to read

**Comment by potatoqualitee** [comment]
https://docs.dbatools.io/#Write-DbaDataTable

i swear that used to work

**Comment by niphlod** [comment]
BTW: never worked, it just worked searching for aliases on the right sidebar, but never looking at the #hash

BTW2: are those detection from google still valid ?

**Comment by potatoqualitee** [comment]
heyy you fixed the redirect! unsure about google, ill let u know if i get an email about it
