### ISSUE TITLE
Old function name still listed on command index

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/docs#27]
![image](https://user-images.githubusercontent.com/16843041/52971803-d4c7aa00-3386-11e9-8524-bb1b9268f964.png)

Looks like this was removed/renamed to `Get-DbaDbRoleMember`, so the link from the index is a dead one.

**Comment by niphlod** [comment]
@potatoqualitee : this looks like the index page on wordpress ....

**Comment by potatoqualitee** [comment]
ahh yes, thank you, it is. I'll fix it all up.

**Comment by potatoqualitee** [comment]
done plus others 👍
