### ISSUE TITLE
Author

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#3]
is there any way to...

* change anything with @ to a twitter hyperlink so ( @gbargsley ) becomes ( [@gbargsley](https://twitter.com/gbargsley) )
* detect an URL like netnerds.net, even though it doesn't have https:// on it, and auto https link it neatly like [netnerds.net](https://netnerds.net)
* detect an URL like http://garry.bargsley.com and then change that to link and look like [garry.bargsley.com](http://garry.bargsley.com)

**Comment by niphlod** [comment]
done, wherever feasible by autolinker.

**Comment by potatoqualitee** [comment]
omfg that was fast and awesome! ty 💃
