### ISSUE TITLE
Expand Search Criteria

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#32]
Hello Niph 🐬 
Can we have two lil radio buttons or something that has search the command name by default but also the option to search all text?

thankssss

**Comment by niphlod** [comment]
@potatoqualitee : see if the solution works, I didn't wanna disrupt user experience.
Basically you type as before, and if what you typed ends up not being a match for a function name, search field switches to "ft:" and enables "full text search". 
New "feature" is also "exposed" when you reach docs.dbatools.io, with a nifty little reminder in the search field.

**Comment by potatoqualitee** [comment]
nice!! it works 💃  thanks so much!
