### ISSUE TITLE
Examples refer to different command than subject

### ISSUE THREAD

**Issue by digitalpajula** [sqlcollaborative/docs#33]
Examples on this page https://docs.dbatools.io/#Dismount-DbaDatabase refer to different commands.

**Comment by potatoqualitee** [comment]
Thanks so much for the report. They are the same commands, just aliased. We expect that most SQL professionals, who are familiar with the `Detach` command, will use `Detach` after searching. Dismount` is distinctly PowerShelly and, in this specific case, we favor the SQL terminology over PS.
