### ISSUE TITLE
Build update

### ISSUE THREAD

**Issue by jensenjkaare** [sqlcollaborative/docs#37]
Hi, when is the build index updated - updates was released last week but not in build index yet.

**Comment by niphlod** [comment]
@wsmelton  did everything correctly. unfortunately GH pages seemed to not be refreshed. Just bumped a minor update and the thingy resumed appropriately. maybe a fallback of issues on github on dec 13. who knows....

**Comment by jensenjkaare** [comment]
Seems not to work - no update available when doing update-module Dbatools

**Comment by niphlod** [comment]
wait. you don't need an updated module to be able to see the udpated index.
Get-DbaBuildReference -Build "12.00.4502" -Update is sufficient for fetching the updated index from internet (which, coincidentally, is the one you can see on https://sqlcollaborative.github.io/builds)

**Comment by jensenjk** [comment]
![image](https://user-images.githubusercontent.com/11940382/71259082-e3307a80-2337-11ea-98e4-5ce8cb01defc.png)
Getting this still

**Comment by niphlod** [comment]
Update-DbaInstance is not Get-DbaBuildReference. Can you post a 

Get-DbaBuildReference -Build "12.00.4502" -Update 

and then again

Get-DbaBuildReference -Build "12.00.4502" -Update

?

**Comment by wsmelton** [comment]
@jensenjk this repository and site have no effect on the dbatools module or commands around the build index.

The index file that contains the build data for SQL Server that we use and maintain is packaged with the module itself. If you want to see the most current version of that file you have two options:
1. Update dbatools to the latest release
1. Run `Get-DbaBuildReference -Update` as Simone mentioned.

The [file in dbatools](https://github.com/sqlcollaborative/dbatools/blob/development/bin/dbatools-buildref-index.json) is current as of 9 Dec.

**Comment by jensenjkaare** [comment]
Thanks – problem solved.
