### ISSUE TITLE
Are the <CommonParameters> listed in the docs anywhere

### ISSUE THREAD

**Issue by Rob-S** [sqlcollaborative/docs#38]
I was unable to find where the <CommonParameters> are listed in the docs, even with a site-specific Google search. If they are there, it might be helpful to include a link to those in the main docs page. Thanks.

**Comment by niphlod** [comment]
hi, CommonParameters are a Powershell "thing" rather than a dbatools one .... https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters
