### ISSUE TITLE
Initial load

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#4]
OKay so when you first go to a page like

https://docs.dbatools.io/#Start-DbaMigration

It takes a second (or longer on slower connections) to load that JSON, then the documentation appears. Totally understandable.

Would it be possible to detect if there is a `#Command-Name`, and show some sort of loading bar under the "Welcome" portion in the middle of the page?

If a person just loads docs.dbatools.io with no specific command name, no need to show loading bar.

**Comment by niphlod** [comment]
check it, I pushed a new version

**Comment by potatoqualitee** [comment]
you're aweeeeeesome! 🏆 💯
