### ISSUE TITLE
Which tool do you use to generate the docs ?

### ISSUE THREAD

**Issue by GMouron** [sqlcollaborative/docs#40]
Hello,

I have developed a big bunch of modules at my job for internal use and I would love to generate a similar doc as the one of dbatools.

I expect that you use a tool for that, is it available somewhere ? (can't find a ref in this repo)

Thanks :)

**Comment by wsmelton** [comment]
We didn't generate it from any specific tool. We use the output of `Get-Help` and generate a [JSON file](https://github.com/sqlcollaborative/docs/blob/master/assets/dbatools-index.json). The resultant page you see from docs.dbatools.io is the result of a contributor developing and writing JavaScript around parsing that file.

**Comment by GMouron** [comment]
OK, thanks for the tip ! 😃
