### ISSUE TITLE
Docs search not working

### ISSUE THREAD

**Issue by Liturgist** [sqlcollaborative/docs#41]
When I visit https://dbatools.io/
and choose "Docs"
I am taken to https://docs.dbatools.io/

I enter "Set-DbatoolsConfig" into the "search" edit control
which takes me nowhere.

**Comment by wsmelton** [comment]
Not at laptop at the moment but it is functioning for me on mobile...

Does the doc page load at all? Can you provide screenshots?

**Comment by wsmelton** [comment]
On my machine/browser it seems to be functioning properly

![image](https://user-images.githubusercontent.com/11204251/85589988-a9ec0680-b609-11ea-8115-0255dea85f16.png)

![image](https://user-images.githubusercontent.com/11204251/85590050-b7a18c00-b609-11ea-8ad6-bd8df0246c38.png)

**Comment by Liturgist** [comment]
It is working for me today. Sorry.
