### ISSUE TITLE
Setup GitHub Action to auto update files

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/docs#43]
@potatoqualitee or @niphlod what is the external JSON file for?

I can set up an action that will pull the index file when we release it to the master branch. Just wondering what that external file is for where the version is being bumped on each release.

**Comment by niphlod** [comment]
Hi @wsmelton , it powers this section of the docs...basically a way to know docs are referring to which version (1) and static links on the side which should always come up (2)

![image](https://user-images.githubusercontent.com/122119/87700631-ec32de80-c796-11ea-80fb-1daa1275afc0.png)

**Comment by wsmelton** [comment]
Ah..ok. That makes sense. I can just add code that increments the value. 

We also have the ability now to manually run task so if we wanted to wait until the release is in PS Gallery before updating this, we have that option. Makes it least the press of a button instead of having to commit.

**Comment by wsmelton** [comment]
@niphlod @potatoqualitee 

Action has been published now for handling updating the assets. It is set to manually be triggered by those that can manage this repository.

1. Go to the Actions tab of the repo
1. Click on the `update-assets` workflow on the left side
1. Click on the `Run workflow` drop-down on the right side
1. Click the `Run workflow` button

![image](https://user-images.githubusercontent.com/11204251/100523960-e9e78480-3179-11eb-9204-5c65302aaf88.png)

Once the container spins up and starts running you will see an entry:

![image](https://user-images.githubusercontent.com/11204251/100523976-01267200-317a-11eb-8a53-19e60bb6fd5c.png)

I set the `bump version` step to output the module version found and the value in the external file ***before it updates***:

![image](https://user-images.githubusercontent.com/11204251/100524001-2e732000-317a-11eb-9c1d-dcd5cc80feee.png)

I use the auto-commit action on the builds site assets as well and works well. So if either file is changed through the workflow it will commit them, otherwise, the workflow will ignore the files.
