### ISSUE TITLE
Resolving to Fully-qualified Name in Update-DbaInstance

### ISSUE THREAD

**Issue by rscottcovington** [sqlcollaborative/docs#44]
We have some servers where the owners have created SPN entries that are interfering with Update-DbaInstance. WINRM errors result.  We think it is due to the function appending the domain name to the servers we pass to it.  Can this be turned off or made to be an option?

**Comment by wsmelton** [comment]
This was reported on sqlcollaborative/dbatools. Closing this issue as it does not pertain to our docs.
