### ISSUE TITLE
[Bug] - [Documentation] Long powershell commands get truncated when rendered on the dbatools.io documentation website

### ISSUE THREAD

**Issue by MarkIannucci** [sqlcollaborative/docs#46]
### Report

Long powershell commands get truncated when rendered on the dbatools.io documentation website:

Example from [Write-DbaDataTable](https://docs.dbatools.io/#Write-DbaDbTableData):
![image](https://user-images.githubusercontent.com/16762974/100178588-61bf6180-2e91-11eb-9ff4-714dc1a97455.png)

In the code we're OK:

https://github.com/sqlcollaborative/dbatools/blob/1640c64014ec5546eaa10396d7d5149993557339/functions/Write-DbaDbTableData.ps1#L109-L115

I'm happy to submit a PR to add a line break, but I'm not sure how I can validate that my addition of a backtick and line feed on line 113 will be rendered by the utility which renders our powershell inline help.

**Comment by niphlod** [comment]
thanks @MarkIannucci for spotting this. 
We're working to have an easier way to generate what the help will look like without spending too much time. 
If you're interested in the "current way" this is the crash course.
Basically ....
- be in "developer mode", e.g. make sure there's a `.git` folder where you're going to make the edits
- edit the inline help of the function
- reload the module with `Import-Module dbatools -Force`
- `Find-DbaCommand -Rebuild` spits out a new `dbatools-index.json` in the `bin` folder
- download sqlcollaborative/docs repo (master branch) and host it in some webserver (static hosting is all you need, so whatever works, from iis to caddy to ... everything). Overwrite `assets\dbatools-index.json` with the one generated in the previous step
- open index.html. it'll do the same thing of docs.dbatools.io

done.

**Comment by potatoqualitee** [comment]
🥳  thanks for the fix, niph
