### ISSUE TITLE
dbatools docs page still shows 1.0.134

### ISSUE THREAD

**Issue by lancasteradam** [sqlcollaborative/docs#49]
The docs page for dbatools is still showing 1.0.134. Let me know if I can be of help to update the docs.

![dbatools docs page](https://user-images.githubusercontent.com/68036988/108643378-3bdd3500-745f-11eb-916c-0ff167b05cfc.png)

**Comment by wsmelton** [comment]
It is controlled via a GitHub Action now that we run manually since we do not have full CI for the module publishing.

**Comment by wsmelton** [comment]
That Action is having issues picking up the right version published to the Gallery

**Comment by wsmelton** [comment]
Hard refresh on the page and it finally shows 137 build now.

![image](https://user-images.githubusercontent.com/11204251/108647316-f7ad5d00-747d-11eb-8c56-8fb72608e88a.png)

**Comment by lancasteradam** [comment]
Thanks, much appreciated.
