### ISSUE TITLE
line breaks

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#5]
Sometimes, it just doesnt line break when it should

https://docs.dbatools.io/#Export-DbaInstance
https://docs.dbatools.io/#Start-DbaMigration

**Comment by potatoqualitee** [comment]
this has been since the beginning btw, no updates today impacted it 💤 night!

**Comment by niphlod** [comment]
maybe it's another "cornercase" that can be easily fixed, I'll inspect more in detail tomorrow

**Comment by niphlod** [comment]
fixed, take a look

**Comment by potatoqualitee** [comment]
perfect! 💯
