### ISSUE TITLE
Update-DbaInstance - Limit Downloads to Language and Processor

### ISSUE THREAD

**Issue by 5uhnjyiwat0ae8ns** [sqlcollaborative/docs#51]
Request - Only download some specified language and processor (x86/x64) editions for updates. 

Optionally - Allow multiple languages and/or processors.

When using "Update-DbaInstance -Download" the number of updates downloaded (and the consequent space used) can be limited by only downloading, say, x64-enu. Otherwise, the space used is quite substantial.

**Comment by wsmelton** [comment]
Please open a feature request issue on sqlcollaborative/dbatools repository.
