### ISSUE TITLE
Second search is affected by the results of the first search

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/docs#53]
It seems that the list of available commands is affected by previous search results. This bug occurs when you already searched for something, but then want to re-start the search. Reproduce steps:

- Click on a Database tag in a tag cloud
- Select all symbols in a search string
- Start typing “instance” in an attempt to show “Connect-DbaInstance” help
- Instead you see only Get-DbaInstanceTrigger

if the first search result haven’t had any matches with that new string, it would’ve switched to ft: search, which is not what I wanted in the first place.

**Comment by niphlod** [comment]
fixed a few days ago
