### ISSUE TITLE
"Commands" link in header points to wrong URL

### ISSUE THREAD

**Issue by chadbaldwin** [sqlcollaborative/docs#54]
The "commands" link at the top of the page points to `https://dbatools.io/functions/` which results in a 404 error.

I believe it should be pointing to `https://dbatools.io/commands/`

**Comment by wsmelton** [comment]
It works on my system and mobile.

You might try a hard refresh of the site in your browser.

**Comment by niphlod** [comment]
the link was incorrect. Fixed it, thanks @chadbaldwin
