### ISSUE TITLE
Test-DbaDiskAlignment isn't rendering

### ISSUE THREAD

**Issue by nocentino** [sqlcollaborative/docs#58]
Hi Everyone, https://docs.dbatools.io/#Test-DbaDiskAlignment isn't rendering.

**Comment by wsmelton** [comment]
Where did you find that link?

The `#` is no longer used so the link would be [https://docs.dbatools.io/Test-DbaDiskAlignment](https://docs.dbatools.io/Test-DbaDiskAlignment)

**Comment by nocentino** [comment]
From here - https://dbatools.io/commands/

**Comment by nocentino** [comment]
Can confirm it works when I remove the `#`

**Comment by wsmelton** [comment]
Ah, okay...that should be a pretty easy fix

**Comment by wsmelton** [comment]
@potatoqualitee pull request submitted, quick find/replace to remove the `#` on the URL references.
