### ISSUE TITLE
better help rendering

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/docs#8]
Managed to do this

![image](https://user-images.githubusercontent.com/122119/45844473-d848fd80-bd22-11e8-841d-d9e8a7aa074f.png)

but the problem/constraint is that multiline statements in the "commandline" of the help are not supported by CBH. So either we go for this representation and go correct the CBH on the few commands that have multiline examples, or we keep it the way they are right now...

e.g. of "mangled multiline"

![image](https://user-images.githubusercontent.com/122119/45844570-2100b680-bd23-11e8-995e-e17721182396.png)

**Comment by potatoqualitee** [comment]
@wsmelton took care of a lot of this last night 🎉 ! Do you have a suggestion for https://docs.dbatools.io/#Export-DbaScript example 7?

**Comment by niphlod** [comment]
>> is the key. See my previous PR on that huge multiline splat on
logshipping function

Il gio 4 ott 2018, 10:43 Chrissy LeMaire <notifications@github.com> ha
scritto:

**Comment by niphlod** [comment]
okay, gonna fix it directly.

**Comment by potatoqualitee** [comment]
We waiting to close this until we are finiished adding PS C:\> or can we now?

**Comment by niphlod** [comment]
no, we can now, the general idea on how to write CBH and how the rendering goes has been "formalized"
